// 58. Problem Statement 
// A server receives login requests from multiple threads. Each thread generates a set of login 
// IDs, and the IDs must be stored in a thread-safe collection because multiple threads may add 
// data concurrently. 
// Write a Java program using a concurrent collection to store the login IDs generated by two 
// threads. After both threads finish, print the total number of stored login records. 

// Input Format 
// The first line contains the number of login records generated by the first thread. 
// The second line contains the number of login records generated by the second thread. 

// Output Format 
// Print: 
// Total Login Records: <number> 

// Code Constraints 
// 0 ≤ N ≤ 100000 

// Sample Input 
// 4000 
// 6000 

// Sample Output 
// Total Login Records: 10000

import java.util.*;
import java.util.concurrent.*;
public class ques58 {
    public static void main(String[] args) throws InterruptedException {
        Scanner sc = new Scanner(System.in);
        int n1 = sc.nextInt();
        int n2 = sc.nextInt();
        ConcurrentLinkedQueue<Integer> loginIds = new ConcurrentLinkedQueue<>();
        Thread t1 = new Thread(()->{
            for(int i=0;i<n1;i++){
                loginIds.add(i);
            }
        });
        Thread t2 = new Thread(()->{
            for(int i=0;i<n2;i++){
                loginIds.add(i);
            }
        });
        t1.start();
        t2.start();
        t1.join();
        t2.join();
        System.out.println("Total login Records: "+loginIds.size());
        

    }
}
